name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 自己的密匙
        TARGET_REPO: zhizhu-video/www    # 自己的仓库地址
        TARGET_BRANCH: gh-pages #这是github默认  你可以自己修改称自己的。但是在pages设置中需要修改
        BUILD_SCRIPT: yarn && yarn run docs:build
        BUILD_DIR: docs/.vitepress/dist/
        CNAME: https://www.zhizhu.video  #这里修改成自己的 Custom domain
